version: "3"
services:
  web:
    # o build define onde o dockerfile esta
    # porem ele necessita ficar na raiz, para conseguir copiar os arquivos index.js, packege.json, etc.
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:password@localhost:3306/db
    networks:
      - mysql-network
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "root"
      # You can use whatever password you like
      MYSQL_PASSWORD: "password"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - mysql-network
# Names our volume
volumes:
  my-db:

networks:
  mysql-network:
    driver: bridge
